//Partially generated by ChatGPT

document.addEventListener("DOMContentLoaded", () => {
    const cards = document.querySelectorAll(".skill-card");
    const buttons = document.querySelectorAll(".filter-buttons button");

    // Convert DOM cards into data objects
    const skills = Array.from(cards).map(card => ({
        element: card,
        category: card.dataset.category
    }));

    buttons.forEach(button => {
        button.addEventListener("click", () => {
            const category = button.dataset.category;

            // Get filtered results
            const filteredSkills = filterSkillsByCategory(skills, category);

            // Hide all cards first
            skills.forEach(skill => {
                skill.element.style.display = "none";
            });

            // Show only filtered cards
            filteredSkills.forEach(skill => {
                skill.element.style.display = "block";
            });
        });
    });

    // Cost calculator logic
    const rateInput = document.getElementById("rate");
    const hoursInput = document.getElementById("hours");
    const calcButton = document.getElementById("calculate-btn");
    const resultDisplay = document.getElementById("total-result");

    calcButton.addEventListener("click", () => {
        const rate = parseFloat(rateInput.value);
        const hours = parseFloat(hoursInput.value);

        if (isNaN(rate) || isNaN(hours)) {
            resultDisplay.textContent = "Please enter valid numbers.";
            return;
        }

        const total = calculateTotalCost(rate, hours);
        resultDisplay.textContent = `Total: $${total.toFixed(2)}`;
    });



});

document.addEventListener("DOMContentLoaded", () => {
    // Find My Match logic
    const matchCategory = document.getElementById("match-category");
    const matchPrice = document.getElementById("match-price");
    const matchBtn = document.getElementById("match-btn");
    const matchResults = document.getElementById("match-results");

// Build skill data from cards
    const cards = document.querySelectorAll(".skill-card");
    const skills = Array.from(cards).map(card => ({
        title: card.querySelector("h3").textContent,
        price: parseFloat(
            card.querySelector(".price").textContent.replace(/[^0-9.]/g, "")
        ),
        provider: card.querySelector(".provider").textContent,
        contact: card.querySelector(".contact").textContent,
        category: card.dataset.category
    }));

    matchBtn.addEventListener("click", () => {
        const category = matchCategory.value;
        const maxPrice = parseFloat(matchPrice.value);

        // Build userNeeds object (required structure)
        const userNeeds = {
            category: category,
            maxPrice: maxPrice
        };

        // Call your function correctly
        const matches = matchSkillsToUser(userNeeds, skills);

        // Clear results
        matchResults.innerHTML = "";

        if (matches.length === 0) {
            matchResults.innerHTML = "<p>No matches found.</p>";
            return;
        }

        // Display matches
        matches.forEach(skill => {
            const div = document.createElement("div");
            div.classList.add("match-item");

            div.innerHTML = `
            <strong>${skill.title}</strong><br>
            $${skill.price}/hr<br>
            ${skill.provider}<br>
            ${skill.contact}
        `;

            matchResults.appendChild(div);
        });
    });
})