//Partially generated by ChatGPT


let skills = []

async function loadSkills() {
    skills = await window.apiService.fetchSkills()
    renderSkills(skills)
}



function renderSkills(skillArray) {
    const container = document.getElementById("skills-container");
    container.innerHTML = "";

    skillArray.forEach(skill => {
        const card = document.createElement("section");
        card.classList.add("skill-card");
        card.dataset.category = skill.category;

        card.innerHTML = `
            <h3>${skill.title}</h3>
            <p>${skill.description}</p>
            <p class="price">$${skill.price}/hr</p>
            <p class="provider">${skill.provider}</p>
            <p class="contact">${skill.contact?skill.contact:"No contact info given"}</p>
        `;

        container.appendChild(card);
    });
}


function filterSkillsByCategory(skills, category) {
    if (category === "all") return skills;
    return skills.filter(skill => skill.category === category);
}

function calculateTotalCost(rate, hours) {
    return rate * hours;
}

function matchSkillsToUser(userNeeds, skills) {
    return skills.filter(skill => {
        const categoryMatch =
            userNeeds.category === "all" ||
            skill.category === userNeeds.category;

        const priceMatch =
            !isNaN(userNeeds.maxPrice) &&
            skill.price <= userNeeds.maxPrice;

        return categoryMatch && priceMatch;
    });
}


document.addEventListener("DOMContentLoaded", () => {

    loadSkills().catch(error => console.log(error))

    const buttons = document.querySelectorAll(".filter-buttons button");

    buttons.forEach(button => {
        button.addEventListener("click", () => {
            const category = button.dataset.category;
            const filtered = filterSkillsByCategory(skills, category);
            renderSkills(filtered);
        });
    });


    const rateInput = document.getElementById("rate");
    const hoursInput = document.getElementById("hours");
    const calcButton = document.getElementById("calculate-btn");
    const resultDisplay = document.getElementById("total-result");

    calcButton.addEventListener("click", () => {
        const rate = parseFloat(rateInput.value);
        const hours = parseFloat(hoursInput.value);

        if (isNaN(rate) || isNaN(hours)) {
            resultDisplay.textContent = "Please enter valid numbers.";
            return;
        }

        const total = calculateTotalCost(rate, hours);
        resultDisplay.textContent = `Total: $${total.toFixed(2)}`;
    });


    const matchCategory = document.getElementById("match-category");
    const matchPrice = document.getElementById("match-price");
    const matchBtn = document.getElementById("match-btn");
    const matchResults = document.getElementById("match-results");

    matchBtn.addEventListener("click", () => {
        const userNeeds = {
            category: matchCategory.value,
            maxPrice: parseFloat(matchPrice.value)
        };

        const matches = matchSkillsToUser(userNeeds, skills);

        matchResults.innerHTML = "";

        if (matches.length === 0) {
            matchResults.innerHTML = "<p>No matches found.</p>";
            return;
        }

        matches.forEach(skill => {
            const div = document.createElement("div");
            div.classList.add("match-item");

            div.innerHTML = `
                <strong>${skill.title}</strong><br>
                $${skill.price}/hr<br>
                ${skill.provider}<br>
                ${skill.contact}
            `;

            matchResults.appendChild(div);
        });

    });

    const form = document.getElementById("create-skill-form");

    form.addEventListener("submit", (e) => {
        e.preventDefault();

        const skillData = {
            title: document.getElementById("skill-title").value,
            category: document.getElementById("skill-category").value,
            price: parseFloat(document.getElementById("skill-price").value),
            description: document.getElementById("skill-description").value
        };

        // POST to database function
        window.apiService.createSkill(skillData).then(async (response) => {
            await loadSkills()
            // Re-render UI
            renderSkills(skills);
        });

        form.reset();
    });


});